### ISSUE TITLE
Set up contribution infrastructure for biojs repos

### ISSUE THREAD

**Issue by DennisSchwartz** [biojs/organisation#21]
# Background

We should set up a formal process for contributing to biojs code repos.
That means the workman, the websites etc.

All input on this discussion is welcome. If there aren't any objections I will implement the process we use at [Repositive](https://github.com/repositive/) and that seems to work very well for us.

# Overview

- The master branch is protected. Contribution can only happen through pull requests.
- Pull requests need to be reviewed by a contributor
- Pull requests are classed into three categories
  - [F] Code changes for enhancements or new features 
  - [B] Bug fixes
  - [S] Support changes. README, settings, deployment files etc.
- PRs are only merged using squashed commits. This provides a cleaner changelog.
- Every PR needs to pass automated tests and linting.
- Test coverage cannot decrease with PRs.
- Test coverage needs to be at least 85% and are at the discretion of the reviewer.

# Todo

- [ ] Create CONTRIBUTE.md file with contribution guidelines
- [ ] Setup Circle CI integration for tests
- [ ] Setup test coverage testing
- [ ] Setup linter and automated linting

# Done
So far I have:
- Enabled CircleCI for the biojs organisation
- Set up testing environment and linter for the new workman repo
